-- SQL setup

CREATE TABLE IF NOT EXISTS survey (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  question TEXT NOT NULL,
  author VARCHAR(100) NOT NULL,
  open BOOLEAN NOT NULL,
  options TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS vote (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  survey_id INTEGER,
  user VARCHAR(100) NOT NULL,
  option TEXT NOT NULL,
  FOREIGN KEY (survey_id) REFERENCES survey(id)
);

